name: Deploy Release

on:
  release:
    types: [published]

jobs:

  deploy-test:
    uses: ./.github/workflows/deploy-web.yml
    with:
      deploy-env: test
    secrets: inherit

  deploy-prod:
    runs-on: ubuntu-latest
    environment: prod
    needs: deploy-test
    steps:
      - run: |
          echo ${{ secrets.ENVIRONMENTSECRET }}
          echo "Deployment is $deploymentvalue"
        name: deploy
        # ...deployment-specific steps
