name: Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  deploy-dev:
    uses: ./.github/workflows/deploy-web.yml
    with:
      deploy-env: dev
    secrets: inherit

  deploy-test:
    uses: ./.github/workflows/deploy-web.yml
    with:
      deploy-env: test
    secrets: inherit

  deploy-prod:
    runs-on: ubuntu-latest
    environment: prod
    needs: deploy-test
    steps:
      - run: |
          echo ${{ secrets.ENVIRONMENTSECRET }}
          echo "Deployment is $deploymentvalue"
        name: deploy
        # ...deployment-specific steps
