name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  deploy-dev:
    uses: ./.github/workflows/deploy-web.yml
    with:
      deploy-env: dev
      app-name: JokeUi396-dev
    secrets: inherit

  deploy-test:
    uses: ./.github/workflows/deploy-web.yml
    with:
      deploy-env: test
      app-name: JokeUi396-test
    secrets: inherit
    needs: deploy-dev

  deploy-prod:
    uses: ./.github/workflows/deploy-web.yml
    with:
      deploy-env: prod
      app-name: JokeUi396
    secrets: inherit
    needs: deploy-dev
