name: Deployment

on:
  push:
    branches:
      - main
      - dev*
  workflow_dispatch:

env:
    deployment-value: "test deployment value"

jobs:

  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:

      - run: |
          .//tools//display-value.ps1 ${{ secrets.ENVIRONMENTSECRET }}
          .//tools//display-value.ps1 ${{ env.deployment-value }}
          printenv

        name: deploy
        shell: pwsh

        # ...deployment-specific steps

  deploy-test:
    runs-on: ubuntu-latest
    environment: test
    needs: deploy-dev 
    steps:
      - run: |
          echo ${{ secrets.ENVIRONMENTSECRET }}
          echo ${{ vars.DEPLOYMENT }}
        name: deploy
        # ...deployment-specific steps

  deploy-prod:
    runs-on: ubuntu-latest
    environment: prod
    needs: deploy-test
    steps:
      - run: |
          echo ${{ secrets.ENVIRONMENTSECRET }}
          echo ${{ vars.DEPLOYMENT }}
        name: deploy
        # ...deployment-specific steps
