name: Deploy Release

on:
  release:
    types: [created]

jobs:

  deploy-test:
    uses: ./.github/workflows/deploy-web.yml
    with:
      deploy-env: test
      app-name: JokeUi396-test
    secrets: inherit

  deploy-prod:
    uses: ./.github/workflows/deploy-web.yml
    with:
      deploy-env: prod
      app-name: JokeUi396
    secrets: inherit
    needs: deploy-test
