name: Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
    deploymentvalue: ${{ vars.DEPLOYMENT }}

jobs:

  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - run: |
          ./display-value.ps1 ${{ secrets.ENVIRONMENTSECRET }}
          echo "deployment value is $env:deploymentvalue"
          dir env:
        name: deploy
        shell: pwsh
        working-directory: tools  

        # ...deployment-specific steps

  deploy-test:
    runs-on: ubuntu-latest
    environment: test
    needs: deploy-dev 
    steps:
      - run: |
          echo ${{ secrets.ENVIRONMENTSECRET }}
          echo "Deployment is $env:deploymentvalue"
        name: deploy
        # ...deployment-specific steps

  deploy-prod:
    runs-on: ubuntu-latest
    environment: prod
    needs: deploy-test
    steps:
      - run: |
          echo ${{ secrets.ENVIRONMENTSECRET }}
          echo "Deployment is $env:deploymentvalue"
        name: deploy
        # ...deployment-specific steps
